esphome:
  name: garage_relay

esp8266:
  board: nodemcuv2
    

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Garage Relay Fallback Hotspot"
    password: !secret wifi_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key_garage_relay
ota:
  - platform: esphome
    password: !secret api_password


http_request:
  useragent: esphome/device
  timeout: 10s
  verify_ssl: false

switch:

  - platform: gpio
    pin: D4
    id: relay
    name: "Garage Door GPIO"
    restore_mode: ALWAYS_ON 
    
    
  - platform: template
    icon: "mdi:arrow-up-down-bold-outline"
    name: "Garage Esp32"
    turn_on_action:
    - switch.turn_on: relay
    - delay: 1000ms
    - switch.turn_off: relay
    
    

sensor:
  - platform: ultrasonic
    trigger_pin: D5
    echo_pin: D6
    name: "Ultrasonic Sensor"
    update_interval: 10s
    id: ultrasonic_sensor1
    filters:
      filter_out: nan
    timeout: 9m

    

  - platform: template
    name: "Garage occupied"
    lambda: |-
      if (id(ultrasonic_sensor1).state > 1) {
        // no car
        return false;
      } else {
        // car is in the garage
        return true;
      }       