esphome:
  name: kitchen_lights
  platform: ESP32
  board: esp32doit-devkit-v1

  
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    # Set this to the IP of the ESP
    static_ip: 192.168.1.226
    # Set this to the IP address of the router. Often ends with .1
    gateway: 192.168.1.1
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0

# Enable logging
logger:


# Enable Home Assistant API
api:

ota:
  - platform: esphome
    password: !secret api_password
#esp32_ble_beacon:
#  type: iBeacon
#  uuid: 'e00c62a3-1a6e-c193-9901-064cc9197e5b'

light:
  - platform: fastled_spi
    chipset: WS2801
    data_pin: GPIO02
    clock_pin: GPIO04
    num_leds: 40
    rgb_order: RGB
    name: "Ledstrip Kitchen"
    effects:
      - addressable_rainbow:
      - addressable_fireworks:
      - addressable_color_wipe:
      - addressable_scan:
      - addressable_twinkle:
      - addressable_random_twinkle:
      - addressable_flicker:
      - random:
      - strobe:
      - flicker:

esp32_ble_tracker:
bluetooth_proxy:

sensor:

  - platform: xiaomi_hhccjcy01
    mac_address: C4:7C:8D:67:4F:D2
    temperature:
      name: "Bonsai2 Temperature"
    moisture:
      name: "Bonsai2 Moisture"
    illuminance:
      name: "Bonsai2 Illuminance"
    conductivity:
      name: "Bonsai2 Soil Conductivity"
    battery_level:
      name: "Bonsai2 Battery Level"
  
    
  - platform: xiaomi_hhccjcy01
    mac_address: C4:7C:8D:67:35:B7
    temperature:
      name: "Eføy Temperature"
    moisture:
      name: "Eføy Moisture"
    illuminance:
      name: "Eføy Illuminance"
    conductivity:
      name: "Eføy Soil Conductivity"
    battery_level:
      name: "Eføy Battery Level"  


